---
- name: run the init
  import_playbook: ../../init/main.yml

- import_playbook: ../../openshift-checks/private/install.yml

- name: configure the control plane
  import_playbook: ../../common/private/control_plane.yml
